Document: jack-mixer
Title: Debian jack-mixer Manual
Author: <insert document author here>
Abstract: This manual describes what jack-mixer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jack-mixer/jack-mixer.sgml.gz

Format: postscript
Files: /usr/share/doc/jack-mixer/jack-mixer.ps.gz

Format: text
Files: /usr/share/doc/jack-mixer/jack-mixer.text.gz

Format: HTML
Index: /usr/share/doc/jack-mixer/html/index.html
Files: /usr/share/doc/jack-mixer/html/*.html
